import { _electron as electron } from 'playwright';
import { mkdir, rm, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve('test-results');
await mkdir(root, { recursive: true });
const data = path.join(root, 'profile'); await rm(data, { recursive: true, force: true });
const rate = 48000, samples = rate * 2;
const fixture = Buffer.alloc(44 + samples * 2);
fixture.write('RIFF'); fixture.writeUInt32LE(fixture.length - 8, 4); fixture.write('WAVEfmt ', 8); fixture.writeUInt32LE(16, 16); fixture.writeUInt16LE(1, 20); fixture.writeUInt16LE(1, 22); fixture.writeUInt32LE(rate, 24); fixture.writeUInt32LE(rate * 2, 28); fixture.writeUInt16LE(2, 32); fixture.writeUInt16LE(16, 34); fixture.write('data', 36); fixture.writeUInt32LE(samples * 2, 40);
for (let i = 0; i < samples; i++) fixture.writeInt16LE(Math.sin(i * 440 / rate * Math.PI * 2) * 4000, 44 + i * 2);
const fixturePath = path.join(root, 'test-tone.wav'); await writeFile(fixturePath, fixture);
let app;
const errors = [];
try {
  app = await electron.launch({ ...(process.env.TAPBACK_EXECUTABLE ? { executablePath: process.env.TAPBACK_EXECUTABLE } : {}), args: [...(process.env.TAPBACK_EXECUTABLE ? [] : ['.']), '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'], env: { ...process.env, TAPBACK_TEST_DATA: data }, timeout: 20000 });
  await app.evaluate(({ systemPreferences }) => { systemPreferences.askForMediaAccess = async () => true; });
  const page = await app.firstWindow();
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.getByRole('heading', { name: 'Soundboard', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Start listening', exact: true }).waitFor({ state: 'visible' });
  await page.screenshot({ path: path.join(root, 'soundboard.png') });
  await page.getByRole('button', { name: 'Tuning', exact: true }).click();
  await page.getByLabel('Volume', { exact: false }).fill('0');
  await page.getByLabel('Detection input').selectOption('manual');
  await page.getByRole('button', { name: 'Soundboard', exact: true }).click();
  await page.getByRole('button', { name: /Give it a test tap/ }).click();
  await page.waitForFunction(() => document.querySelector('.session-stat b')?.textContent === '01');
  await page.getByRole('button', { name: /Rubber room/ }).click();
  await page.getByRole('button', { name: 'Boing!', exact: true }).click();
  await page.getByRole('button', { name: /Recording studio/ }).click();
  await page.locator('input[type=file]').setInputFiles(fixturePath);
  await page.getByLabel('Sound name').waitFor();
  await page.getByLabel('Sound name').fill('Custom boop');
  await page.getByLabel('Trim start', { exact: false }).fill('0.15');
  await page.getByLabel('Trim end', { exact: false }).fill('1.55');
  await page.getByRole('button', { name: 'Save sound', exact: true }).click();
  await page.getByRole('textbox', { name: 'Rename Custom boop' }).waitFor();
  await page.getByRole('button', { name: 'Exclude Custom boop' }).click();
  await page.getByRole('button', { name: 'Include Custom boop' }).click();
  await page.getByRole('button', { name: 'Start recording', exact: true }).click();
  await page.getByRole('button', { name: 'Stop recording', exact: true }).waitFor({ timeout: 10000 });
  await page.waitForTimeout(1200);
  await page.getByRole('button', { name: 'Stop recording', exact: true }).click();
  await page.getByLabel('Sound name').waitFor();
  await page.getByLabel('Sound name').fill('Recorded reaction');
  await page.getByRole('button', { name: 'Save sound', exact: true }).click();
  await page.getByRole('textbox', { name: 'Rename Recorded reaction' }).waitFor();
  await page.screenshot({ path: path.join(root, 'studio.png') });
  const persisted = await page.evaluate(() => window.tapback.state());
  assert.equal(persisted.clips.length, 2); assert.equal(persisted.clips[0].name, 'Custom boop');
  assert.ok(Math.abs(persisted.clips[0].duration - 1.4) < 0.01);
  const recordingPeak = await page.evaluate(async id => {
    const bytes = new Uint8Array(await window.tapback.readClip(id)), samples = new DataView(bytes.buffer); let peak = 0;
    for (let i = 44; i + 1 < bytes.length; i += 2) peak = Math.max(peak, Math.abs(samples.getInt16(i, true)));
    return peak;
  }, persisted.clips[1].id);
  assert.ok(recordingPeak > 100, `Recorded fake microphone should contain audio, got peak ${recordingPeak}`);
  const packPath = path.join(root, 'test-export.tapback');
  await app.evaluate(({ dialog }, filePath) => {
    dialog.showSaveDialog = async () => ({ canceled: false, filePath });
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filePath] });
  }, packPath);
  await page.getByRole('button', { name: 'Export pack' }).click();
  await page.getByRole('status').filter({ hasText: 'Your sound pack is ready to share.' }).waitFor();
  await page.getByRole('button', { name: 'Import pack' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.clip-row').length === 4);
  await page.getByRole('button', { name: 'Tuning', exact: true }).click();
  await page.getByLabel('Detection input').selectOption('microphone');
  await page.getByRole('button', { name: 'Start listening', exact: true }).click();
  await page.getByRole('button', { name: 'Listening', exact: true }).waitFor();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].hide());
  await page.waitForFunction(() => parseInt(document.querySelector('.input-meter b')?.textContent || '0') > 0, { timeout: 5000 });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].show());
  await page.getByRole('button', { name: 'Calibrate ambient noise' }).click();
  await page.getByRole('button', { name: 'Keep still for 3 seconds…' }).waitFor();
  await page.getByRole('button', { name: 'Calibrate ambient noise' }).waitFor({ timeout: 7000 });
  await page.screenshot({ path: path.join(root, 'tuning.png') });
  await page.getByRole('button', { name: 'Listening', exact: true }).click();
  const sensorResult = await page.evaluate(async () => {
    let samples = 0; let last = null;
    const off = window.tapback.on('sensor', data => { if (data.type === 'sample') { samples++; last = data; } });
    const result = await window.tapback.sensorStart();
    if (result.type === 'ready') await new Promise(resolve => setTimeout(resolve, 1200));
    off(); return { ...result, samples, last };
  });
  assert.ok(['ready', 'unavailable'].includes(sensorResult.type));
  if (sensorResult.type === 'ready') assert.ok(sensorResult.samples > 20, 'Native adapter must deliver a sustained stream, not only a ready status.');
  await page.evaluate(() => window.tapback.sensorStop());
  await page.getByRole('button', { name: 'Soundboard', exact: true }).click();
  await page.getByRole('button', { name: 'Mute', exact: true }).click();
  const before = await page.locator('.session-stat b').first().textContent();
  await page.getByRole('button', { name: /Give it a test tap/ }).click();
  assert.equal(await page.locator('.session-stat b').first().textContent(), before);
  await page.waitForTimeout(400);
  const state = await page.evaluate(() => window.tapback.state());
  assert.equal(state.settings.mute, true);
  assert.equal(JSON.parse(await readFile(path.join(data, 'settings.json'), 'utf8')).mute, true);
  assert.equal(errors.length, 0, errors.join('\n'));
  await writeFile(path.join(root, 'smoke-report.json'), JSON.stringify({ passed: true, packaged: !!process.env.TAPBACK_EXECUTABLE, checks: ['window load', 'manual reaction', 'pack selection', 'sound preview', 'audio import', 'trimmed WAV save', 'include/exclude', 'non-silent microphone recording with fake device', 'recording save', 'pack export and import through IPC', 'mic detection start/pause', 'hidden-window audio processing', 'calibration', 'native capability response', 'mute', 'settings persisted to disk'], sensor: sensorResult, recordingPeak, rendererErrors: errors }, null, 2));
  console.log('PASS: Desktop smoke checks completed; screenshots and report saved.');
} catch (e) {
  if (app) { const pages = app.windows(); if (pages.length) { await pages[0].screenshot({ path: path.join(root, 'failure.png') }).catch(() => {}); console.error(await pages[0].locator('body').innerText().catch(() => '')); } }
  throw e;
} finally { await app?.close(); }
